version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    image: local-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/nginx-logs:/var/log/nginx  # Mount host directory for logs
    networks:
      - nginx-network

  python-app:
    build:
      context: ./python  # Set the build context to the python directory
    image: local-python-app
    container_name: python_app
    expose:
      - "8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
